language: python
python:
    - "nightly"
    - "3.6-dev"
    - 3.5
    - 3.4
    - 3.3
install:
    - pip install "pytest" --upgrade
    - pip install codecov --upgrade
script:
    - py.test
after_success:
    - codecov

matrix:
    allow_failures:
        - python: nightly
